# Dockerfile

# Usa una imagen base oficial
FROM nginx:stable

# Copia el archivo html al directorio de contenido web por defecto de Nginx
COPY index.html /usr/share/nginx/html/index.html

# Se indica el puerto
EXPOSE 80