name: Variables Workflow

on:
  workflow_dispatch:

jobs:
  job1:
    runs-on: ubuntu-latest
    outputs:
      var2: ${{ steps.var2_output.outputs.var2 }}

    steps:
      - name: Definir e imprimir variable local
        run: |
          var1="1"
          echo "Variable local: $var1"
      
      - name: Definir variable de entorno
        id: var2_output
        run: |
          echo "var2=2" >> $GITHUB_OUTPUT

      - name: Imprimir variable de entorno
        run: |
          echo "Variable de entorno: ${{ steps.var2_output.outputs.var2 }}"

  job2:
    runs-on: ubuntu-latest
    
    steps:
      - name: Definir output
        id: create_output
        run: |
          echo "var_step_output=valor" >> $GITHUB_OUTPUT

      - name: Imprimir output
        run: |
          echo "Salida output: ${{ steps.create_output.outputs.var_step_output }}"

  job3:
    runs-on: ubuntu-latest
    needs: [job1]
    outputs:
      var3: ${{ steps.var3_output.outputs.var3 }}
    
    steps:
      - name: Imprimir valor de var2
        run: |
          echo "var2 = ${{ needs.job1.outputs.var2 }}"
      
      - name: Definir output var3
        id: var3_output
        run: |
          echo "var3=3" >> $GITHUB_OUTPUT
  
  job4:
    runs-on: ubuntu-latest
    needs: [job3]

    steps:
      - name: Imprimir var3
        run: |
          echo "Valor de var3: ${{ needs.job3.outputs.var3 }}"
  
  job5:
    runs-on: ubuntu-latest

    steps:
      - name: Imprimir variables predefinidas
        run: |
          echo "Nombre del repositorio: ${GITHUB_REPOSITORY##*/}"
          echo "Nombre de la rama: ${GITHUB_REF_NAME}"
          echo "Nombre del evento que activó el workflow: ${GITHUB_EVENT_NAME}"